# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8266a858-5614-4df9-92b8-7e4a5cd05ac6";
    fsType = "btrfs";
    options = [ "subvol=@nixos" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/8266a858-5614-4df9-92b8-7e4a5cd05ac6";
    fsType = "btrfs";
    options = [ "subvol=@nixos_home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/8266a858-5614-4df9-92b8-7e4a5cd05ac6";
    fsType = "btrfs";
    options = [ "subvol=@nixos_nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6496-9B32";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/arch_home" = {
    device = "/dev/disk/by-uuid/8266a858-5614-4df9-92b8-7e4a5cd05ac6";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/mnt/arcade" = {
    device = "/dev/disk/by-uuid/f0e67ebf-4af6-4a8e-9c08-196e26926db6";
    fsType = "btrfs";
    options = [ "nofail" ];
  };

  fileSystems."/mnt/game" = {
    device = "/dev/disk/by-uuid/1b3dad64-6da1-45fe-86af-ac0db2c4c963";
    fsType = "btrfs";
    options = [ "nofail" ];
  };

  fileSystems."/mnt/pirate" = {
    device = "/dev/disk/by-uuid/787EAE207EADD762";
    fsType = "ntfs3";
    options = [
      "uid=1000"
      "prealloc"
      "nofail"
      "x-systemd.automount"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
