# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8266a858-5614-4df9-92b8-7e4a5cd05ac6";
      fsType = "btrfs";
      options = [ "subvol=@nixos" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8266a858-5614-4df9-92b8-7e4a5cd05ac6";
      fsType = "btrfs";
      options = [ "subvol=@nixos_home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/8266a858-5614-4df9-92b8-7e4a5cd05ac6";
      fsType = "btrfs";
      options = [ "subvol=@nixos_nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6496-9B32";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/arcade" =
    { device = "/dev/disk/by-uuid/4ED8B1B8D8B19EA1";
      fsType = "ntfs3";
      options = [ "defaults" "uid=1000" "gid=1000" "umask=0022" "prealloc" "nofail" ];
    };

  fileSystems."/mnt/game" =
    { device = "/dev/disk/by-uuid/ee1440b5-2673-893e-b116-50befc960c6c";
      fsType = "btrfs";
    };

  fileSystems."/mnt/pirate" =
    { device = "/dev/disk/by-uuid/787EAE207EADD762";
      fsType = "ntfs3";
      options = [ "defaults" "uid=1000" "gid=1000" "umask=0022" "prealloc" "nofail" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
